Update release.yml with jwst-pure-parallel release.yml per stsci instructions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,15 +1,133 @@
-name: build
+name: release
 
 on:
   release:
     types: [ released ]
-  pull_request:
   workflow_dispatch:
+    inputs:
+      git_tag:
+        description: 'Target Git Tag'
+        required: true
+        type: string
+
+permissions: {}
 
 jobs:
+  validate:
+    if: (github.repository == 'spacetelescope/jwst-pure-parallel') && (github.event_name == 'workflow_dispatch')
+    runs-on: ubuntu-latest
+    outputs:
+      job_tag: ${{ steps.tag_name.outputs.tag }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+        with:
+          fetch-depth: 0 # Fetches all history and tags
+      - name: Validate Tag Exists
+        id: tag_name
+        run: |
+          USER_TAG="${{ github.event.inputs.git_tag }}"
+          # Check if the tag exists in the repository
+          if git rev-parse --verify --quiet "refs/tags/$USER_TAG" > /dev/null; then
+            echo "✅ Tag '$USER_TAG' is valid."
+            echo "tag=refs/tags/$USER_TAG" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Error: Tag '$USER_TAG' does not exist in this repository."
+            exit 1
+          fi
+
+
   build:
-    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
-    with:
-      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
-    secrets:
-      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
+    needs: [validate]
+    if: ${{ !cancelled() && (needs.validate.result == 'success' || needs.validate.result == 'skipped') }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get Release Tag From Release
+        if: (github.repository == 'spacetelescope/jwst-pure-parallel') && (github.event_name == 'release')
+        run: |
+          echo "TAG=${{ github.ref }}" >> $GITHUB_ENV
+          echo "Release being made from ${{ env.TAG }} "
+      - name: Get Release Tag from User
+        if: (github.repository == 'spacetelescope/jwst-pure-parallel') && (github.event_name == 'workflow_dispatch')
+        run: |
+          echo "TAG=${{ needs.validate.outputs.job_tag }}" >> $GITHUB_ENV
+          echo "Release being made from ${{ env.TAG }} "
+      - name: Checkout
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+        with:
+          ref: ${{ env.TAG }}
+          persist-credentials: false
+          fetch-depth: 0
+          fetch-tags: true
+      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
+        with:
+          python-version: ${{ vars.PYTHON_VERSION }}
+
+      - name: Build the package
+        run: |
+          python -m pip install build twine
+          python -m build --sdist --wheel .
+          ls -lh dist
+          python -m twine check --strict dist/*
+
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: additional-pylons
+          path: dist/
+
+  publish-to-testpypi:
+    needs: [build]
+    if: (github.repository == 'spacetelescope/jwst-pure-parallel')
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
+      attestations: write
+    # To add required reviewers before publish,
+    # edit the protection rules in GitHub Settings:
+    # Settings > Environments > pypi > Add required reviewers
+    environment:
+      name: testpypi
+      url: https://test.pypi.org/p/jwpure
+    steps:
+      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          pattern: additional-pylons*
+          path: dist/
+          merge-multiple: true
+
+      - uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
+        with:
+          subject-path: "dist/*"
+
+      # To upload to PyPI without a token, add this workflow file as a Trusted Publisher in the project settings on the PyPI website
+      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
+        with:
+          repository-url: https://test.pypi.org/legacy/
+
+  publish-to-pypi:
+    needs: [build, publish-to-testpypi]
+    if: (!cancelled() && github.repository == 'spacetelescope/jwst-pure-parallel')
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
+      attestations: write
+    # To add required reviewers before publish,
+    # edit the protection rules in GitHub Settings:
+    # Settings > Environments > pypi > Add required reviewers
+    environment:
+      name: pypi
+      url: https://pypi.org/p/jwpure
+    steps:
+      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          pattern: additional-pylons*
+          path: dist/
+          merge-multiple: true
+
+      - uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
+        with:
+          subject-path: "dist/*"
+
+      # To upload to PyPI without a token, add this workflow file as a Trusted Publisher in the project settings on the PyPI website
+      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
